### ISSUE TITLE
Compare to Simple Binary Encoding (SBE) - High Performance Message Codec

### ISSUE THREAD

**Issue by nietras** [Sergio0694/BinaryPack#13]
Performance looks great for BinaryPack but perhaps compare to something like SBE.

https://github.com/real-logic/simple-binary-encoding

The difference here is SBE is mainly based on code generation at build time.

**Comment by Sergio0694** [comment]
Hi, I can't see a NuGet link on the repo, do you know if it is available as a NuGet package at all?

**Comment by MendelMonteiro** [comment]
It's availble here: https://www.nuget.org/packages/Adaptive.SBE/
Also, https://github.com/real-logic/simple-binary-encoding/wiki/Csharp-User-Guide

**Comment by nietras** [comment]
Closing as stale, feel free to open if interested in addressing this :)
