### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by ismail0234** [Sergio0694/BinaryPack#33]
I really like and using the project. I found that some types are not supported. Can you add support for these?

- Hashset
- ConcurrentDictionary

**Comment by Sergio0694** [comment]
As you can see in the readme:

> **DISCLAIMER:** this library is provided as is, and it's no longer being actively maintained. **BinaryPack** was developed just for fun and it has not been tested in critical production environments. It does work fine in the scenarios described in this document (eg. I'm using this library to handle local cache files in some of my apps), but if you're looking for a more widely used and well tested library for fast binary serialization (that also offers better flexibility and customization), I'd recommend looking into [`MessagePack-CSharp`](https://github.com/neuecc/MessagePack-CSharp) first.

So... Nope 😄
